language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - ng build pdfjs-box --prod
  - ng build --prod --base-href .
  - cp dist/pdfjs/index.html dist/pdfjs/404.html
deploy:
  - provider: script
    script: cd projects/pdfjs-box; npm version patch -m "[ci skip]"; cd ../../dist/pdfjs-box; npm version patch -m "[ci skip]"
    skip_cleanup: true
    on:
      branch: /^pdfjs.*$/
  - provider: script
    script: git commit -m "[ci skip]" package-lock.json; npm version patch -m "[ci skip]"
    skip_cleanup: true
    on:
      branch:
        only:
          - /^pdfjs.*$/
          - /^config.*$/
          - /^website.*$/
  - provider: script
    script: git push https://$GITHUB_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git master
    skip_cleanup: true
    on:
      branch:
        only:
          - /^pdfjs.*$/
          - /^config.*$/
          - /^website.*$/
  - provider: releases
    user: "$GITHUB_USER"
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      branch:
        only:
          - /^pdfjs.*$/
          - /^config.*$/
          - /^website.*$/
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    local-dir: "dist/pdfjs"
    on:
      branch:
        only:
          - /^pdfjs.*$/
          - /^config.*$/
          - /^website.*$/
  - provider: script
    script: npm publish dist/pdfjs-box
    skip_cleanup: true
    on:
      branch: /^pdfjs.*$/
